import { getMTRBusETAMessage, MTRBusETAResponse } from '@services/bus/mtr';

describe('test can getMTRBusETAMessage', () => {
  const res: MTRBusETAResponse = {
    appRefreshTimeInSecond: '60',
    busStop: [
      {
        bus: [
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '401',
            departureTimeText: '6 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '881',
            departureTimeText: '14 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1361',
            departureTimeText: '22 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '526',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1901',
            departureTimeText: '31 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2441',
            departureTimeText: '40 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D010',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '0',
            arrivalTimeText: '即將到站/已離開',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '43',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '479',
            arrivalTimeText: '7 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '556',
            departureTimeText: '9 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '959',
            arrivalTimeText: '15 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1036',
            departureTimeText: '17 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1439',
            arrivalTimeText: '23 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1516',
            departureTimeText: '25 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1979',
            arrivalTimeText: '32 分鐘',
            busId: '526',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2056',
            departureTimeText: '34 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2529',
            arrivalTimeText: '42 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2641',
            departureTimeText: '44 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: '1',
        busStopId: 'K73-D020',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '73',
            arrivalTimeText: '1 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '100',
            departureTimeText: '1 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '585',
            arrivalTimeText: '9 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '612',
            departureTimeText: '10 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1065',
            arrivalTimeText: '17 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1092',
            departureTimeText: '18 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1545',
            arrivalTimeText: '25 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1572',
            departureTimeText: '26 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2085',
            arrivalTimeText: '34 分鐘',
            busId: '526',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2112',
            departureTimeText: '35 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2669',
            arrivalTimeText: '44 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2692',
            departureTimeText: '44 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D030',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '183',
            arrivalTimeText: '3 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '200',
            departureTimeText: '3 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '693',
            arrivalTimeText: '11 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '710',
            departureTimeText: '11 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1173',
            arrivalTimeText: '19 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1190',
            departureTimeText: '19 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1653',
            arrivalTimeText: '27 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1670',
            departureTimeText: '27 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2193',
            arrivalTimeText: '36 分鐘',
            busId: '526',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2210',
            departureTimeText: '36 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D040',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '262',
            arrivalTimeText: '4 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '288',
            departureTimeText: '4 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '772',
            arrivalTimeText: '12 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '797',
            departureTimeText: '13 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1252',
            arrivalTimeText: '20 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1277',
            departureTimeText: '21 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1732',
            arrivalTimeText: '28 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1757',
            departureTimeText: '29 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2272',
            arrivalTimeText: '37 分鐘',
            busId: '526',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2297',
            departureTimeText: '38 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D050',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '325',
            arrivalTimeText: '5 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '359',
            departureTimeText: '5 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '833',
            arrivalTimeText: '13 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '868',
            departureTimeText: '14 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1313',
            arrivalTimeText: '21 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1348',
            departureTimeText: '22 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1793',
            arrivalTimeText: '29 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1828',
            departureTimeText: '30 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2333',
            arrivalTimeText: '38 分鐘',
            busId: '526',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2368',
            departureTimeText: '39 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D060',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '376',
            arrivalTimeText: '6 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '426',
            departureTimeText: '7 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '885',
            arrivalTimeText: '14 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '934',
            departureTimeText: '15 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1365',
            arrivalTimeText: '22 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1414',
            departureTimeText: '23 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1845',
            arrivalTimeText: '30 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1894',
            departureTimeText: '31 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2385',
            arrivalTimeText: '39 分鐘',
            busId: '526',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2434',
            departureTimeText: '40 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D070',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '42',
            arrivalTimeText: '即將到站/已離開',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '61',
            departureTimeText: '1 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '516',
            arrivalTimeText: '8 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '535',
            departureTimeText: '8 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1022',
            arrivalTimeText: '17 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1042',
            departureTimeText: '17 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1502',
            arrivalTimeText: '25 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1522',
            departureTimeText: '25 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1982',
            arrivalTimeText: '33 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2002',
            departureTimeText: '33 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2522',
            arrivalTimeText: '42 分鐘',
            busId: '526',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2542',
            departureTimeText: '42 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: '1',
        busStopId: 'K73-D080',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '0',
            arrivalTimeText: '即將到站/已離開',
            busId: '513',
            busLocation: {
              latitude: 22.452975,
              longitude: 114.00607833333333,
            },
            busRemark: null,
            departureTimeInSecond: '59',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '289',
            arrivalTimeText: '4 分鐘',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '350',
            departureTimeText: '5 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '763',
            arrivalTimeText: '12 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '824',
            departureTimeText: '13 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1267',
            arrivalTimeText: '21 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1329',
            departureTimeText: '22 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1747',
            arrivalTimeText: '29 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1809',
            departureTimeText: '30 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2227',
            arrivalTimeText: '37 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2289',
            departureTimeText: '38 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: '1',
        busStopId: 'K73-D090',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '80',
            arrivalTimeText: '1 分鐘',
            busId: '513',
            busLocation: {
              latitude: 22.452975,
              longitude: 114.00607833333333,
            },
            busRemark: null,
            departureTimeInSecond: '104',
            departureTimeText: '1 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '371',
            arrivalTimeText: '6 分鐘',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '395',
            departureTimeText: '6 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '845',
            arrivalTimeText: '14 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '869',
            departureTimeText: '14 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1351',
            arrivalTimeText: '22 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1376',
            departureTimeText: '22 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1831',
            arrivalTimeText: '30 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1856',
            departureTimeText: '30 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2311',
            arrivalTimeText: '38 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2336',
            departureTimeText: '38 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D100',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '251',
            arrivalTimeText: '4 分鐘',
            busId: '513',
            busLocation: {
              latitude: 22.452975,
              longitude: 114.00607833333333,
            },
            busRemark: null,
            departureTimeInSecond: '288',
            departureTimeText: '4 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '543',
            arrivalTimeText: '9 分鐘',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '579',
            departureTimeText: '9 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1017',
            arrivalTimeText: '16 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '1053',
            departureTimeText: '17 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1521',
            arrivalTimeText: '25 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1557',
            departureTimeText: '25 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2001',
            arrivalTimeText: '33 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2037',
            departureTimeText: '33 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2481',
            arrivalTimeText: '41 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2517',
            departureTimeText: '41 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D110',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '301',
            arrivalTimeText: '5 分鐘',
            busId: '513',
            busLocation: {
              latitude: 22.452975,
              longitude: 114.00607833333333,
            },
            busRemark: null,
            departureTimeInSecond: '336',
            departureTimeText: '5 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '593',
            arrivalTimeText: '9 分鐘',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '628',
            departureTimeText: '10 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1067',
            arrivalTimeText: '17 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '1102',
            departureTimeText: '18 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1571',
            arrivalTimeText: '26 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1606',
            departureTimeText: '26 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2051',
            arrivalTimeText: '34 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2086',
            departureTimeText: '34 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2531',
            arrivalTimeText: '42 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2566',
            departureTimeText: '42 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D120',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '403',
            arrivalTimeText: '6 分鐘',
            busId: '513',
            busLocation: {
              latitude: 22.452975,
              longitude: 114.00607833333333,
            },
            busRemark: null,
            departureTimeInSecond: '450',
            departureTimeText: '7 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '694',
            arrivalTimeText: '11 分鐘',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '741',
            departureTimeText: '12 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1168',
            arrivalTimeText: '19 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '1215',
            departureTimeText: '20 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1668',
            arrivalTimeText: '27 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1715',
            departureTimeText: '28 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2148',
            arrivalTimeText: '35 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2195',
            departureTimeText: '36 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2628',
            arrivalTimeText: '43 分鐘',
            busId: '518',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2675',
            departureTimeText: '44 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D130',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '529',
            arrivalTimeText: '8 分鐘',
            busId: '513',
            busLocation: {
              latitude: 22.452975,
              longitude: 114.00607833333333,
            },
            busRemark: null,
            departureTimeInSecond: '593',
            departureTimeText: '9 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '820',
            arrivalTimeText: '13 分鐘',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '884',
            departureTimeText: '14 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1294',
            arrivalTimeText: '21 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '1358',
            departureTimeText: '22 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1794',
            arrivalTimeText: '29 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1854',
            departureTimeText: '30 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2274',
            arrivalTimeText: '37 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2334',
            departureTimeText: '38 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D140',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '0',
            arrivalTimeText: '即將到站/已離開',
            busId: '536',
            busLocation: {
              latitude: 22.468057666666663,
              longitude: 113.99919483333333,
            },
            busRemark: null,
            departureTimeInSecond: '0',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '716',
            arrivalTimeText: '11 分鐘',
            busId: '513',
            busLocation: {
              latitude: 22.452975,
              longitude: 114.00607833333333,
            },
            busRemark: null,
            departureTimeInSecond: '757',
            departureTimeText: '12 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1007',
            arrivalTimeText: '16 分鐘',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '1049',
            departureTimeText: '17 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1481',
            arrivalTimeText: '24 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '1523',
            departureTimeText: '25 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1958',
            arrivalTimeText: '32 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2000',
            departureTimeText: '33 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2438',
            arrivalTimeText: '40 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2480',
            departureTimeText: '41 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: '1',
        busStopId: 'K73-D150',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '2',
            arrivalTimeText: '即將到站/已離開',
            busId: '536',
            busLocation: {
              latitude: 22.468057666666663,
              longitude: 113.99919483333333,
            },
            busRemark: null,
            departureTimeInSecond: '2',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '759',
            arrivalTimeText: '12 分鐘',
            busId: '513',
            busLocation: {
              latitude: 22.452975,
              longitude: 114.00607833333333,
            },
            busRemark: null,
            departureTimeInSecond: '759',
            departureTimeText: '12 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1051',
            arrivalTimeText: '17 分鐘',
            busId: '504',
            busLocation: {
              latitude: 22.449806166666669,
              longitude: 114.0217215,
            },
            busRemark: null,
            departureTimeInSecond: '1051',
            departureTimeText: '17 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '1525',
            arrivalTimeText: '25 分鐘',
            busId: '519',
            busLocation: {
              latitude: 22.446139499999997,
              longitude: 114.026667,
            },
            busRemark: null,
            departureTimeInSecond: '1525',
            departureTimeText: '25 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2001',
            arrivalTimeText: '33 分鐘',
            busId: '534',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '0',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
          {
            arrivalTimeInSecond: '2481',
            arrivalTimeText: '41 分鐘',
            busId: '525',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '0',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_TH',
          },
        ],
        busIcon: null,
        busStopId: 'K73-D160',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '221',
            departureTimeText: '3 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '761',
            departureTimeText: '12 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1301',
            departureTimeText: '21 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '504',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1841',
            departureTimeText: '30 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '108000',
            arrivalTimeText: '',
            busId: '519',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2321',
            departureTimeText: '38 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U010',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '287',
            arrivalTimeText: '4 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '314',
            departureTimeText: '5 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '827',
            arrivalTimeText: '13 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '854',
            departureTimeText: '14 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1367',
            arrivalTimeText: '22 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1394',
            departureTimeText: '23 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1907',
            arrivalTimeText: '31 分鐘',
            busId: '504',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1934',
            departureTimeText: '32 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2387',
            arrivalTimeText: '39 分鐘',
            busId: '519',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2414',
            departureTimeText: '40 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U020',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '458',
            arrivalTimeText: '7 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '496',
            departureTimeText: '8 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '998',
            arrivalTimeText: '16 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1036',
            departureTimeText: '17 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1538',
            arrivalTimeText: '25 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1576',
            departureTimeText: '26 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2078',
            arrivalTimeText: '34 分鐘',
            busId: '504',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2116',
            departureTimeText: '35 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2558',
            arrivalTimeText: '42 分鐘',
            busId: '519',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2596',
            departureTimeText: '43 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U030',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '548',
            arrivalTimeText: '9 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '610',
            departureTimeText: '10 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1088',
            arrivalTimeText: '18 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1150',
            departureTimeText: '19 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1628',
            arrivalTimeText: '27 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1690',
            departureTimeText: '28 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2168',
            arrivalTimeText: '36 分鐘',
            busId: '504',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2230',
            departureTimeText: '37 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2648',
            arrivalTimeText: '44 分鐘',
            busId: '519',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2710',
            departureTimeText: '45 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U040',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '7',
            arrivalTimeText: '即將到站/已離開',
            busId: '526',
            busLocation: {
              latitude: 22.464214166666672,
              longitude: 114.0037355,
            },
            busRemark: null,
            departureTimeInSecond: '57',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '640',
            arrivalTimeText: '10 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '691',
            departureTimeText: '11 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1180',
            arrivalTimeText: '19 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1231',
            departureTimeText: '20 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1720',
            arrivalTimeText: '28 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1771',
            departureTimeText: '29 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2260',
            arrivalTimeText: '37 分鐘',
            busId: '504',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2311',
            departureTimeText: '38 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: '1',
        busStopId: 'K73-U050',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '110',
            arrivalTimeText: '1 分鐘',
            busId: '526',
            busLocation: {
              latitude: 22.464214166666672,
              longitude: 114.0037355,
            },
            busRemark: null,
            departureTimeInSecond: '156',
            departureTimeText: '2 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '745',
            arrivalTimeText: '12 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '790',
            departureTimeText: '13 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1285',
            arrivalTimeText: '21 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1330',
            departureTimeText: '22 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1825',
            arrivalTimeText: '30 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1870',
            departureTimeText: '31 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2365',
            arrivalTimeText: '39 分鐘',
            busId: '504',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2410',
            departureTimeText: '40 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U060',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '249',
            arrivalTimeText: '4 分鐘',
            busId: '526',
            busLocation: {
              latitude: 22.464214166666672,
              longitude: 114.0037355,
            },
            busRemark: null,
            departureTimeInSecond: '297',
            departureTimeText: '4 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '886',
            arrivalTimeText: '14 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '933',
            departureTimeText: '15 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1426',
            arrivalTimeText: '23 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1473',
            departureTimeText: '24 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1966',
            arrivalTimeText: '32 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2013',
            departureTimeText: '33 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2506',
            arrivalTimeText: '41 分鐘',
            busId: '504',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2553',
            departureTimeText: '42 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U070',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '408',
            arrivalTimeText: '6 分鐘',
            busId: '526',
            busLocation: {
              latitude: 22.464214166666672,
              longitude: 114.0037355,
            },
            busRemark: null,
            departureTimeInSecond: '463',
            departureTimeText: '7 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1039',
            arrivalTimeText: '17 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1094',
            departureTimeText: '18 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1579',
            arrivalTimeText: '26 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1634',
            departureTimeText: '27 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2119',
            arrivalTimeText: '35 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2174',
            departureTimeText: '36 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2659',
            arrivalTimeText: '44 分鐘',
            busId: '504',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2714',
            departureTimeText: '45 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U080',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '147',
            arrivalTimeText: '2 分鐘',
            busId: '518',
            busLocation: {
              latitude: 22.451665166666665,
              longitude: 114.00848616666666,
            },
            busRemark: null,
            departureTimeInSecond: '165',
            departureTimeText: '2 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '672',
            arrivalTimeText: '11 分鐘',
            busId: '526',
            busLocation: {
              latitude: 22.464214166666672,
              longitude: 114.0037355,
            },
            busRemark: null,
            departureTimeInSecond: '690',
            departureTimeText: '11 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1309',
            arrivalTimeText: '21 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1327',
            departureTimeText: '22 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1849',
            arrivalTimeText: '30 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1867',
            departureTimeText: '31 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2389',
            arrivalTimeText: '39 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2407',
            departureTimeText: '40 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: '2',
        busStopId: 'K73-U090',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '0',
            arrivalTimeText: '即將到站/已離開',
            busId: '525',
            busLocation: {
              latitude: 22.450839499999997,
              longitude: 114.02294166666667,
            },
            busRemark: null,
            departureTimeInSecond: '22',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '249',
            arrivalTimeText: '4 分鐘',
            busId: '518',
            busLocation: {
              latitude: 22.451665166666665,
              longitude: 114.00848616666666,
            },
            busRemark: null,
            departureTimeInSecond: '308',
            departureTimeText: '5 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '774',
            arrivalTimeText: '12 分鐘',
            busId: '526',
            busLocation: {
              latitude: 22.464214166666672,
              longitude: 114.0037355,
            },
            busRemark: null,
            departureTimeInSecond: '834',
            departureTimeText: '13 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1408',
            arrivalTimeText: '23 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1466',
            departureTimeText: '24 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1948',
            arrivalTimeText: '32 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2006',
            departureTimeText: '33 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2488',
            arrivalTimeText: '41 分鐘',
            busId: '513',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2546',
            departureTimeText: '42 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: '1',
        busStopId: 'K73-U100',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '206',
            arrivalTimeText: '3 分鐘',
            busId: '525',
            busLocation: {
              latitude: 22.450839499999997,
              longitude: 114.02294166666667,
            },
            busRemark: null,
            departureTimeInSecond: '274',
            departureTimeText: '4 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '492',
            arrivalTimeText: '8 分鐘',
            busId: '518',
            busLocation: {
              latitude: 22.451665166666665,
              longitude: 114.00848616666666,
            },
            busRemark: null,
            departureTimeInSecond: '560',
            departureTimeText: '9 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1018',
            arrivalTimeText: '16 分鐘',
            busId: '526',
            busLocation: {
              latitude: 22.464214166666672,
              longitude: 114.0037355,
            },
            busRemark: null,
            departureTimeInSecond: '1085',
            departureTimeText: '18 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1646',
            arrivalTimeText: '27 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '1713',
            departureTimeText: '28 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2186',
            arrivalTimeText: '36 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '2253',
            departureTimeText: '37 分鐘',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U110',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
      {
        bus: [
          {
            arrivalTimeInSecond: '0',
            arrivalTimeText: '即將到站/已離開',
            busId: '534',
            busLocation: {
              latitude: 22.4452595,
              longitude: 114.02492583333333,
            },
            busRemark: null,
            departureTimeInSecond: '-50',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '427',
            arrivalTimeText: '7 分鐘',
            busId: '525',
            busLocation: {
              latitude: 22.450839499999997,
              longitude: 114.02294166666667,
            },
            busRemark: null,
            departureTimeInSecond: '427',
            departureTimeText: '7 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '713',
            arrivalTimeText: '11 分鐘',
            busId: '518',
            busLocation: {
              latitude: 22.451665166666665,
              longitude: 114.00848616666666,
            },
            busRemark: null,
            departureTimeInSecond: '713',
            departureTimeText: '11 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1239',
            arrivalTimeText: '20 分鐘',
            busId: '526',
            busLocation: {
              latitude: 22.464214166666672,
              longitude: 114.0037355,
            },
            busRemark: null,
            departureTimeInSecond: '1239',
            departureTimeText: '20 分鐘',
            isDelayed: '0',
            isScheduled: '0',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '1869',
            arrivalTimeText: '31 分鐘',
            busId: '514',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '0',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
          {
            arrivalTimeInSecond: '2409',
            arrivalTimeText: '40 分鐘',
            busId: '536',
            busLocation: {
              latitude: 0,
              longitude: 0,
            },
            busRemark: null,
            departureTimeInSecond: '0',
            departureTimeText: '即將開出/已離開',
            isDelayed: '0',
            isScheduled: '1',
            lineRef: 'K73_YLW',
          },
        ],
        busIcon: null,
        busStopId: 'K73-U120',
        busStopRemark: null,
        busStopStatus: null,
        busStopStatusRemarkContent: null,
        busStopStatusRemarkTitle: null,
        busStopStatusTime: null,
        isSuspended: '0',
      },
    ],
    caseNumber: 0,
    caseNumberDetail: '',
    footerRemarks:
      '系統正進行測試，預計到站時間或與實際情況有誤差，請為行程預留充裕時間。班次及到站時間只供參考，或會因應情況調整，恕不另行通知。',
    routeColour: '',
    routeName: 'K73',
    routeStatus: '0',
    routeStatusColour: 'black',
    routeStatusRemarkContent: null,
    routeStatusRemarkFooterRemark: '',
    routeStatusRemarkTitle: null,
    routeStatusTime: '2021/06/05 10:19',
    status: '0',
  };

  test('Can get first stop ETA message', () => {
    expect(getMTRBusETAMessage('K73-D010', res)).toEqual(`預計到站時間如下⌚
————————————————————
1. 6 分鐘  預定班次
2. 14 分鐘  預定班次
3. 22 分鐘  預定班次
4. 31 分鐘  預定班次
5. 40 分鐘  預定班次`);
  });

  test('Can get subsequence stop ETA message', () => {
    expect(getMTRBusETAMessage('K73-D020', res)).toEqual(`預計到站時間如下⌚
————————————————————
1. 即將到站/已離開
2. 7 分鐘  預定班次
3. 15 分鐘  預定班次
4. 23 分鐘  預定班次
5. 32 分鐘  預定班次
6. 42 分鐘  預定班次`);
  });
});
