const BUS_SCENE_ID = 'bus';
const MTR_SCENE_ID = 'mtr';
const LRT_SCENE_ID = 'LRT';

// Bus
const CHECK_CIRCULAR_ACTION = 'B00';
const DIRECTION_ACTION = 'B01';
const STOPS_ACTION = 'B02';
const BUS_ETA_ACTION = 'B03';

const CHECK_CIRCULAR_ACTION_REGEX = new RegExp(`^${CHECK_CIRCULAR_ACTION},`);
const DIRECTION_ACTION_REGEX = new RegExp(`^${DIRECTION_ACTION},`);
const STOPS_ACTION_REGEX = new RegExp(`^${STOPS_ACTION},`);
const BUS_ETA_ACTION_REGEX = new RegExp(`^${BUS_ETA_ACTION},`);

// MTR
const STATIONS_ACTION = 'M00';
const MTR_ETA_ACTION = 'M01';

const STATIONS_ACTION_REGEX = new RegExp(`^${STATIONS_ACTION},`);
const MTR_ETA_ACTION_REGEX = new RegExp(`^${MTR_ETA_ACTION},`);

// LRT
const ZONES_ACTION = 'L00';
const LRT_ETA_ACTION = 'L01';

const ZONES_ACTION_REGEX = new RegExp(`^${ZONES_ACTION},`);
const LRT_ETA_ACTION_REGEX = new RegExp(`^${LRT_ETA_ACTION},`);

const ENV = process.env.NODE_ENV || 'devlopment';
const TG_TOKEN = process.env.TG_KEY;
const TG_DEV_TOKEN = process.env.TG_DEV_KEY;
const SENTRY_TOKEN = process.env.SENTRY_KEY;
const GA_TID = process.env.GA_TID;
const HKETA_GRAPHQL = process.env.HKETA_GRAPHQL;

module.exports = Object.freeze({
    BUS_SCENE_ID,
    MTR_SCENE_ID,
    LRT_SCENE_ID,
    CHECK_CIRCULAR_ACTION,
    DIRECTION_ACTION,
    STOPS_ACTION,
    BUS_ETA_ACTION,
    CHECK_CIRCULAR_ACTION_REGEX,
    DIRECTION_ACTION_REGEX,
    STOPS_ACTION_REGEX,
    BUS_ETA_ACTION_REGEX,
    STATIONS_ACTION,
    MTR_ETA_ACTION,
    STATIONS_ACTION_REGEX,
    MTR_ETA_ACTION_REGEX,
    ZONES_ACTION,
    LRT_ETA_ACTION,
    ZONES_ACTION_REGEX,
    LRT_ETA_ACTION_REGEX,
    ENV,
    TG_TOKEN,
    TG_DEV_TOKEN,
    SENTRY_TOKEN,
    GA_TID,
    HKETA_GRAPHQL
});
